# Generated by Django 3.1.7 on 2021-03-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
